version: "3.2"

services:
  login-service:
    image: dis/login-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - main
    
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
       
networks:
  main:
